// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwINdK1XJux0SehCoE5XSdB8ND-PXlLc',
    appId: '1:854083840690:web:f6f637a1fbe0874248f7ab',
    messagingSenderId: '854083840690',
    projectId: 'htyw-ab76e',
    authDomain: 'htyw-ab76e.firebaseapp.com',
    databaseURL: 'https://htyw-ab76e-default-rtdb.firebaseio.com',
    storageBucket: 'htyw-ab76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IMEvHTwx7VSYJaW1wqtSMSIveHNgZX8',
    appId: '1:854083840690:android:bb61bf378a3fc76548f7ab',
    messagingSenderId: '854083840690',
    projectId: 'htyw-ab76e',
    databaseURL: 'https://htyw-ab76e-default-rtdb.firebaseio.com',
    storageBucket: 'htyw-ab76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKbov9e3lyoGiYtzFoHYwtOmdDscsjsbo',
    appId: '1:854083840690:ios:3d7e1b25c9ba5b5448f7ab',
    messagingSenderId: '854083840690',
    projectId: 'htyw-ab76e',
    databaseURL: 'https://htyw-ab76e-default-rtdb.firebaseio.com',
    storageBucket: 'htyw-ab76e.appspot.com',
    iosClientId: '854083840690-jalrlihr2kffk0rdkr9pp5rcq13qrub6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKbov9e3lyoGiYtzFoHYwtOmdDscsjsbo',
    appId: '1:854083840690:ios:3d7e1b25c9ba5b5448f7ab',
    messagingSenderId: '854083840690',
    projectId: 'htyw-ab76e',
    databaseURL: 'https://htyw-ab76e-default-rtdb.firebaseio.com',
    storageBucket: 'htyw-ab76e.appspot.com',
    iosClientId: '854083840690-jalrlihr2kffk0rdkr9pp5rcq13qrub6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFwINdK1XJux0SehCoE5XSdB8ND-PXlLc',
    appId: '1:854083840690:web:8840845a9a8d89a648f7ab',
    messagingSenderId: '854083840690',
    projectId: 'htyw-ab76e',
    authDomain: 'htyw-ab76e.firebaseapp.com',
    databaseURL: 'https://htyw-ab76e-default-rtdb.firebaseio.com',
    storageBucket: 'htyw-ab76e.appspot.com',
  );
}
